CREATE SEQUENCE PURCHASE_SEQ START WITH 10000 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS PURCHASE
(
    ID      NUMERIC(19) NOT NULL,
    MSISDN  INTEGER     NOT NULL,
    CREATED TIMESTAMP   NOT NULL
);

ALTER TABLE PURCHASE
    ADD CONSTRAINT PK_PURCHASE PRIMARY KEY (ID);
ALTER TABLE PURCHASE
    ADD CONSTRAINT UQ_PURCHASE_MSISDN UNIQUE (MSISDN);



CREATE SEQUENCE SUBSCRIPTION_SEQ START WITH 10000 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS SUBSCRIPTION
(
    ID      NUMERIC(19) NOT NULL,
    MSISDN  INTEGER     NOT NULL,
    CREATED TIMESTAMP   NOT NULL
);

ALTER TABLE SUBSCRIPTION
    ADD CONSTRAINT PK_SUBSCRIPTION PRIMARY KEY (ID);
ALTER TABLE SUBSCRIPTION
    ADD CONSTRAINT UQ_SUBSCRIPTION_MSISDN UNIQUE (MSISDN);
