version: '3'

services:
  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    ports:
      - "5432:5432/tcp"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres

  sub:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: ./subscriber/
    container_name: sub
    depends_on:
      - db
    ports:
      - "8081:8081/tcp"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  pub:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: ./publisher/
    container_name: pub
    depends_on:
      - sub
    ports:
      - "8080:8080/tcp"
    environment:
      - SUB_URL=http://host.docker.internal:8081/message